language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t syedhusyn/complex-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true syedhusyn/complex-test npm run test -- --coverage

after_success:
  - docker build -t syedhusyn/multi-client ./client
  - docker build -t syedhusyn/multi-nginx ./nginx
  - docker build -t syedhusyn/multi-server ./server
  - docker build -t syedhusyn/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push syedhusyn/multi-client
  - docker push syedhusyn/multi-nginx
  - docker push syedhusyn/multi-server
  - docker push syedhusyn/multi-worker

